<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.CN.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.4.0.15</Version>
    <AssemblyName>KeitaToolbox</AssemblyName>
    <RootNamespace>KeitaToolbox</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
